// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyALUJFBqs2mg5kbU2ATy_8zFBQTSW0CR80",
      authDomain: "kioskui-devops.firebaseapp.com",
      projectId: "kioskui-devops",
      storageBucket: "kioskui-devops.appspot.com",
      messagingSenderId: "549677909381",
      appId: "1:549677909381:web:7a755a6509886fa46970ec",
      measurementId: "G-5G21E7SCER");
}
